package modele;

// Generated Jun 9, 2014 4:05:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Exemplaire generated by hbm2java
 */
public class Exemplaire implements java.io.Serializable {

	private BigDecimal idexemplaire;
	private Film film;
	private boolean disponible;

	public Exemplaire() {
	}

	public Exemplaire(BigDecimal idexemplaire, Film film, boolean disponible) {
		this.idexemplaire = idexemplaire;
		this.film = film;
		this.disponible = disponible;
	}

	public BigDecimal getIdexemplaire() {
		return this.idexemplaire;
	}

	public void setIdexemplaire(BigDecimal idexemplaire) {
		this.idexemplaire = idexemplaire;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public boolean isDisponible() {
		return this.disponible;
	}

	public void setDisponible(boolean disponible) {
		this.disponible = disponible;
	}

}
