package modele;

// Generated Jun 9, 2014 4:05:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Forfait generated by hbm2java
 */
public class Forfait implements java.io.Serializable {

	private BigDecimal idforfait;
	private String nom;
	private BigDecimal coutforfait;
	private BigDecimal locationmax;
	private BigDecimal dureemax;
	private Set utilisateurs = new HashSet(0);

	public Forfait() {
	}

	public Forfait(BigDecimal idforfait, String nom, BigDecimal coutforfait,
			BigDecimal locationmax, BigDecimal dureemax) {
		this.idforfait = idforfait;
		this.nom = nom;
		this.coutforfait = coutforfait;
		this.locationmax = locationmax;
		this.dureemax = dureemax;
	}
	
	public Forfait(String nom, BigDecimal coutforfait,
			BigDecimal locationmax, BigDecimal dureemax) {
		this.nom = nom;
		this.coutforfait = coutforfait;
		this.locationmax = locationmax;
		this.dureemax = dureemax;
	}

	public Forfait(BigDecimal idforfait, String nom, BigDecimal coutforfait,
			BigDecimal locationmax, BigDecimal dureemax, Set utilisateurs) {
		this.idforfait = idforfait;
		this.nom = nom;
		this.coutforfait = coutforfait;
		this.locationmax = locationmax;
		this.dureemax = dureemax;
		this.utilisateurs = utilisateurs;
	}
	
	public Forfait(String nom, BigDecimal coutforfait,
			BigDecimal locationmax, BigDecimal dureemax, Set utilisateurs) {
		this.nom = nom;
		this.coutforfait = coutforfait;
		this.locationmax = locationmax;
		this.dureemax = dureemax;
		this.utilisateurs = utilisateurs;
	}

	public BigDecimal isIdforfait() {
		return this.idforfait;
	}

	public void setIdforfait(BigDecimal idforfait) {
		this.idforfait = idforfait;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public BigDecimal getCoutforfait() {
		return this.coutforfait;
	}

	public void setCoutforfait(BigDecimal coutforfait) {
		this.coutforfait = coutforfait;
	}

	public BigDecimal getLocationmax() {
		return this.locationmax;
	}

	public void setLocationmax(BigDecimal locationmax) {
		this.locationmax = locationmax;
	}

	public BigDecimal getDureemax() {
		return this.dureemax;
	}

	public void setDureemax(BigDecimal dureemax) {
		this.dureemax = dureemax;
	}

	public Set getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
