package modele;

// Generated Jun 9, 2014 4:05:17 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Locationfilm generated by hbm2java
 */
public class Locationfilm implements java.io.Serializable {

	private LocationfilmId id;
	private Date datedelocation;
	private Date datederetour;

	public Locationfilm() {
	}

	public Locationfilm(LocationfilmId id, Date datedelocation,
			Date datederetour) {
		this.id = id;
		this.datedelocation = datedelocation;
		this.datederetour = datederetour;
	}

	public LocationfilmId getId() {
		return this.id;
	}

	public void setId(LocationfilmId id) {
		this.id = id;
	}

	public Date getDatedelocation() {
		return this.datedelocation;
	}

	public void setDatedelocation(Date datedelocation) {
		this.datedelocation = datedelocation;
	}

	public Date getDatederetour() {
		return this.datederetour;
	}

	public void setDatederetour(Date datederetour) {
		this.datederetour = datederetour;
	}

}
