package modele;

// Generated Jun 9, 2014 4:05:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * LocationfilmId generated by hbm2java
 */
public class LocationfilmId implements java.io.Serializable {

	private BigDecimal idutilisateur;
	private BigDecimal idexemplaire;

	public LocationfilmId() {
	}

	public LocationfilmId(BigDecimal idutilisateur, BigDecimal idexemplaire) {
		this.idutilisateur = idutilisateur;
		this.idexemplaire = idexemplaire;
	}

	public BigDecimal getIdutilisateur() {
		return this.idutilisateur;
	}

	public void setIdutilisateur(BigDecimal idutilisateur) {
		this.idutilisateur = idutilisateur;
	}

	public BigDecimal getIdexemplaire() {
		return this.idexemplaire;
	}

	public void setIdexemplaire(BigDecimal idexemplaire) {
		this.idexemplaire = idexemplaire;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocationfilmId))
			return false;
		LocationfilmId castOther = (LocationfilmId) other;

		return ((this.getIdutilisateur() == castOther.getIdutilisateur()) || (this
				.getIdutilisateur() != null
				&& castOther.getIdutilisateur() != null && this
				.getIdutilisateur().equals(castOther.getIdutilisateur())))
				&& ((this.getIdexemplaire() == castOther.getIdexemplaire()) || (this
						.getIdexemplaire() != null
						&& castOther.getIdexemplaire() != null && this
						.getIdexemplaire().equals(castOther.getIdexemplaire())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdutilisateur() == null ? 0 : this.getIdutilisateur()
						.hashCode());
		result = 37
				* result
				+ (getIdexemplaire() == null ? 0 : this.getIdexemplaire()
						.hashCode());
		return result;
	}

}
