package modele;

// Generated Jun 9, 2014 4:05:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personne generated by hbm2java
 */
public class Personne implements java.io.Serializable {

	private BigDecimal idpersonne;
	private String nom;
	private String prenom;
	private Date datedenaissance;
	private String lieudenaissance;
	private String biographie;
	private String photo;
	private Set implications = new HashSet(0);

	public Personne() {
	}

	public Personne(BigDecimal idpersonne, String nom) {
		this.idpersonne = idpersonne;
		this.nom = nom;
	}
	
	public Personne(String nom) {
		this.idpersonne = idpersonne;
		this.nom = nom;
	}

	public Personne(BigDecimal idpersonne, String nom, String prenom,
			Date datedenaissance, String lieudenaissance, String biographie,
			String photo, Set implications) {
		this.idpersonne = idpersonne;
		this.nom = nom;
		this.prenom = prenom;
		this.datedenaissance = datedenaissance;
		this.lieudenaissance = lieudenaissance;
		this.biographie = biographie;
		this.photo = photo;
		this.implications = implications;
	}
	
	public Personne(String nom, String prenom,
			Date datedenaissance, String lieudenaissance, String biographie,
			String photo, Set implications) {
		this.nom = nom;
		this.prenom = prenom;
		this.datedenaissance = datedenaissance;
		this.lieudenaissance = lieudenaissance;
		this.biographie = biographie;
		this.photo = photo;
		this.implications = implications;
	}

	public BigDecimal getIdpersonne() {
		return this.idpersonne;
	}

	public void setIdpersonne(BigDecimal idpersonne) {
		this.idpersonne = idpersonne;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public Date getDatedenaissance() {
		return this.datedenaissance;
	}

	public void setDatedenaissance(Date datedenaissance) {
		this.datedenaissance = datedenaissance;
	}

	public String getLieudenaissance() {
		return this.lieudenaissance;
	}

	public void setLieudenaissance(String lieudenaissance) {
		this.lieudenaissance = lieudenaissance;
	}

	public String getBiographie() {
		return this.biographie;
	}

	public void setBiographie(String biographie) {
		this.biographie = biographie;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public Set getImplications() {
		return this.implications;
	}

	public void setImplications(Set implications) {
		this.implications = implications;
	}

}
