package modele;

// Generated Jun 9, 2014 4:05:17 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Typepersonne generated by hbm2java
 */
public class Typepersonne implements java.io.Serializable {

	private BigDecimal idtypepersonne;
	private String typepersonne;
	private Set implications = new HashSet(0);

	public Typepersonne() {
	}

	public Typepersonne(BigDecimal idtypepersonne, String typepersonne) {
		this.idtypepersonne = idtypepersonne;
		this.typepersonne = typepersonne;
	}

	public Typepersonne(BigDecimal idtypepersonne, String typepersonne,
			Set implications) {
		this.idtypepersonne = idtypepersonne;
		this.typepersonne = typepersonne;
		this.implications = implications;
	}

	public BigDecimal getIdtypepersonne() {
		return this.idtypepersonne;
	}

	public void setIdtypepersonne(BigDecimal idtypepersonne) {
		this.idtypepersonne = idtypepersonne;
	}

	public String getTypepersonne() {
		return this.typepersonne;
	}

	public void setTypepersonne(String typepersonne) {
		this.typepersonne = typepersonne;
	}

	public Set getImplications() {
		return this.implications;
	}

	public void setImplications(Set implications) {
		this.implications = implications;
	}

}
