package modele;
import java.math.BigDecimal;

/**
 * VueFilmId generated by hbm2java
 */
public class VueFilmId implements java.io.Serializable {

	private BigDecimal idfilm;
	private String titre;
	private short anneesortie;
	private String nompays;
	private String langue;
	private String libellegenre;
	private String nomprenom;
	private String typepersonne;
	private String resume;

	public VueFilmId() {
	}

	public VueFilmId(BigDecimal idfilm, String titre, short anneesortie,
			String nompays, String libellegenre, String typepersonne,
			String resume) {
		this.idfilm = idfilm;
		this.titre = titre;
		this.anneesortie = anneesortie;
		this.nompays = nompays;
		this.libellegenre = libellegenre;
		this.typepersonne = typepersonne;
		this.resume = resume;
	}

	public VueFilmId(BigDecimal idfilm, String titre, short anneesortie,
			String nompays, String langue, String libellegenre,
			String nomprenom, String typepersonne, String resume) {
		this.idfilm = idfilm;
		this.titre = titre;
		this.anneesortie = anneesortie;
		this.nompays = nompays;
		this.langue = langue;
		this.libellegenre = libellegenre;
		this.nomprenom = nomprenom;
		this.typepersonne = typepersonne;
		this.resume = resume;
	}

	public BigDecimal getIdfilm() {
		return this.idfilm;
	}

	public void setIdfilm(BigDecimal idfilm) {
		this.idfilm = idfilm;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public short getAnneesortie() {
		return this.anneesortie;
	}

	public void setAnneesortie(short anneesortie) {
		this.anneesortie = anneesortie;
	}

	public String getNompays() {
		return this.nompays;
	}

	public void setNompays(String nompays) {
		this.nompays = nompays;
	}

	public String getLangue() {
		return this.langue;
	}

	public void setLangue(String langue) {
		this.langue = langue;
	}

	public String getLibellegenre() {
		return this.libellegenre;
	}

	public void setLibellegenre(String libellegenre) {
		this.libellegenre = libellegenre;
	}

	public String getNomprenom() {
		return this.nomprenom;
	}

	public void setNomprenom(String nomprenom) {
		this.nomprenom = nomprenom;
	}

	public String getTypepersonne() {
		return this.typepersonne;
	}

	public void setTypepersonne(String typepersonne) {
		this.typepersonne = typepersonne;
	}

	public String getResume() {
		return this.resume;
	}

	public void setResume(String resume) {
		this.resume = resume;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VueFilmId))
			return false;
		VueFilmId castOther = (VueFilmId) other;

		return ((this.getIdfilm() == castOther.getIdfilm()) || (this
				.getIdfilm() != null && castOther.getIdfilm() != null && this
				.getIdfilm().equals(castOther.getIdfilm())))
				&& ((this.getTitre() == castOther.getTitre()) || (this
						.getTitre() != null && castOther.getTitre() != null && this
						.getTitre().equals(castOther.getTitre())))
				&& (this.getAnneesortie() == castOther.getAnneesortie())
				&& ((this.getNompays() == castOther.getNompays()) || (this
						.getNompays() != null && castOther.getNompays() != null && this
						.getNompays().equals(castOther.getNompays())))
				&& ((this.getLangue() == castOther.getLangue()) || (this
						.getLangue() != null && castOther.getLangue() != null && this
						.getLangue().equals(castOther.getLangue())))
				&& ((this.getLibellegenre() == castOther.getLibellegenre()) || (this
						.getLibellegenre() != null
						&& castOther.getLibellegenre() != null && this
						.getLibellegenre().equals(castOther.getLibellegenre())))
				&& ((this.getNomprenom() == castOther.getNomprenom()) || (this
						.getNomprenom() != null
						&& castOther.getNomprenom() != null && this
						.getNomprenom().equals(castOther.getNomprenom())))
				&& ((this.getTypepersonne() == castOther.getTypepersonne()) || (this
						.getTypepersonne() != null
						&& castOther.getTypepersonne() != null && this
						.getTypepersonne().equals(castOther.getTypepersonne())))
				&& ((this.getResume() == castOther.getResume()) || (this
						.getResume() != null && castOther.getResume() != null && this
						.getResume().equals(castOther.getResume())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdfilm() == null ? 0 : this.getIdfilm().hashCode());
		result = 37 * result
				+ (getTitre() == null ? 0 : this.getTitre().hashCode());
		result = 37 * result + this.getAnneesortie();
		result = 37 * result
				+ (getNompays() == null ? 0 : this.getNompays().hashCode());
		result = 37 * result
				+ (getLangue() == null ? 0 : this.getLangue().hashCode());
		result = 37
				* result
				+ (getLibellegenre() == null ? 0 : this.getLibellegenre()
						.hashCode());
		result = 37 * result
				+ (getNomprenom() == null ? 0 : this.getNomprenom().hashCode());
		result = 37
				* result
				+ (getTypepersonne() == null ? 0 : this.getTypepersonne()
						.hashCode());
		result = 37 * result
				+ (getResume() == null ? 0 : this.getResume().hashCode());
		return result;
	}

}
