package modele;
/**
 * VueFilm generated by hbm2java
 */
public class VueFilm implements java.io.Serializable {

	private VueFilmId id;

	public VueFilm() {
	}

	public VueFilm(VueFilmId id) {
		this.id = id;
	}

	public VueFilmId getId() {
		return this.id;
	}

	public void setId(VueFilmId id) {
		this.id = id;
	}

}
