// default package
// Generated 2014-06-09 11:13:01 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Annonce generated by hbm2java
 */
public class Annonce implements java.io.Serializable {

	private BigDecimal idannonce;
	private Film film;
	private String announce;

	public Annonce() {
	}

	public Annonce(BigDecimal idannonce, Film film, String announce) {
		this.idannonce = idannonce;
		this.film = film;
		this.announce = announce;
	}

	public BigDecimal getIdannonce() {
		return this.idannonce;
	}

	public void setIdannonce(BigDecimal idannonce) {
		this.idannonce = idannonce;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public String getAnnounce() {
		return this.announce;
	}

	public void setAnnounce(String announce) {
		this.announce = announce;
	}

}
