// default package
// Generated 2014-06-09 11:13:01 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Forfait generated by hbm2java
 */
public class Forfait implements java.io.Serializable {

	private boolean idforfait;
	private String nom;
	private BigDecimal coutforfait;
	private BigDecimal locationmax;
	private BigDecimal dureemax;
	private Set utilisateurs = new HashSet(0);

	public Forfait() {
	}

	public Forfait(boolean idforfait, String nom, BigDecimal coutforfait,
			BigDecimal locationmax, BigDecimal dureemax) {
		this.idforfait = idforfait;
		this.nom = nom;
		this.coutforfait = coutforfait;
		this.locationmax = locationmax;
		this.dureemax = dureemax;
	}

	public Forfait(boolean idforfait, String nom, BigDecimal coutforfait,
			BigDecimal locationmax, BigDecimal dureemax, Set utilisateurs) {
		this.idforfait = idforfait;
		this.nom = nom;
		this.coutforfait = coutforfait;
		this.locationmax = locationmax;
		this.dureemax = dureemax;
		this.utilisateurs = utilisateurs;
	}

	public boolean isIdforfait() {
		return this.idforfait;
	}

	public void setIdforfait(boolean idforfait) {
		this.idforfait = idforfait;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public BigDecimal getCoutforfait() {
		return this.coutforfait;
	}

	public void setCoutforfait(BigDecimal coutforfait) {
		this.coutforfait = coutforfait;
	}

	public BigDecimal getLocationmax() {
		return this.locationmax;
	}

	public void setLocationmax(BigDecimal locationmax) {
		this.locationmax = locationmax;
	}

	public BigDecimal getDureemax() {
		return this.dureemax;
	}

	public void setDureemax(BigDecimal dureemax) {
		this.dureemax = dureemax;
	}

	public Set getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
