// default package
// Generated 2014-06-09 11:13:01 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * ImplicationId generated by hbm2java
 */
public class ImplicationId implements java.io.Serializable {

	private BigDecimal idfilm;
	private BigDecimal idpersonne;
	private BigDecimal idtypepersonne;

	public ImplicationId() {
	}

	public ImplicationId(BigDecimal idfilm, BigDecimal idpersonne,
			BigDecimal idtypepersonne) {
		this.idfilm = idfilm;
		this.idpersonne = idpersonne;
		this.idtypepersonne = idtypepersonne;
	}

	public BigDecimal getIdfilm() {
		return this.idfilm;
	}

	public void setIdfilm(BigDecimal idfilm) {
		this.idfilm = idfilm;
	}

	public BigDecimal getIdpersonne() {
		return this.idpersonne;
	}

	public void setIdpersonne(BigDecimal idpersonne) {
		this.idpersonne = idpersonne;
	}

	public BigDecimal getIdtypepersonne() {
		return this.idtypepersonne;
	}

	public void setIdtypepersonne(BigDecimal idtypepersonne) {
		this.idtypepersonne = idtypepersonne;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImplicationId))
			return false;
		ImplicationId castOther = (ImplicationId) other;

		return ((this.getIdfilm() == castOther.getIdfilm()) || (this
				.getIdfilm() != null && castOther.getIdfilm() != null && this
				.getIdfilm().equals(castOther.getIdfilm())))
				&& ((this.getIdpersonne() == castOther.getIdpersonne()) || (this
						.getIdpersonne() != null
						&& castOther.getIdpersonne() != null && this
						.getIdpersonne().equals(castOther.getIdpersonne())))
				&& ((this.getIdtypepersonne() == castOther.getIdtypepersonne()) || (this
						.getIdtypepersonne() != null
						&& castOther.getIdtypepersonne() != null && this
						.getIdtypepersonne().equals(
								castOther.getIdtypepersonne())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdfilm() == null ? 0 : this.getIdfilm().hashCode());
		result = 37
				* result
				+ (getIdpersonne() == null ? 0 : this.getIdpersonne()
						.hashCode());
		result = 37
				* result
				+ (getIdtypepersonne() == null ? 0 : this.getIdtypepersonne()
						.hashCode());
		return result;
	}

}
