// default package
// Generated 2014-06-09 11:13:01 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	private BigDecimal idutilisateur;
	private Forfait forfait;
	private String nomfamille;
	private String prenom;
	private String utilisateurtype;
	private String telephone;
	private String courriel;
	private BigDecimal numerocivique;
	private String rue;
	private String ville;
	private String province;
	private String codepostal;
	private Date datenaissance;
	private String identificateur;
	private String motdepasse;
	private String cartecredittype;
	private Long cartecreditnumero;
	private Date cartecreditdateexp;
	private Short cartecreditcvv;

	public Utilisateur() {
	}

	public Utilisateur(BigDecimal idutilisateur, String nomfamille,
			String prenom, String utilisateurtype, String telephone,
			String courriel, BigDecimal numerocivique, String rue,
			String ville, String province, String codepostal,
			Date datenaissance, String identificateur, String motdepasse) {
		this.idutilisateur = idutilisateur;
		this.nomfamille = nomfamille;
		this.prenom = prenom;
		this.utilisateurtype = utilisateurtype;
		this.telephone = telephone;
		this.courriel = courriel;
		this.numerocivique = numerocivique;
		this.rue = rue;
		this.ville = ville;
		this.province = province;
		this.codepostal = codepostal;
		this.datenaissance = datenaissance;
		this.identificateur = identificateur;
		this.motdepasse = motdepasse;
	}

	public Utilisateur(BigDecimal idutilisateur, Forfait forfait,
			String nomfamille, String prenom, String utilisateurtype,
			String telephone, String courriel, BigDecimal numerocivique,
			String rue, String ville, String province, String codepostal,
			Date datenaissance, String identificateur, String motdepasse,
			String cartecredittype, Long cartecreditnumero,
			Date cartecreditdateexp, Short cartecreditcvv) {
		this.idutilisateur = idutilisateur;
		this.forfait = forfait;
		this.nomfamille = nomfamille;
		this.prenom = prenom;
		this.utilisateurtype = utilisateurtype;
		this.telephone = telephone;
		this.courriel = courriel;
		this.numerocivique = numerocivique;
		this.rue = rue;
		this.ville = ville;
		this.province = province;
		this.codepostal = codepostal;
		this.datenaissance = datenaissance;
		this.identificateur = identificateur;
		this.motdepasse = motdepasse;
		this.cartecredittype = cartecredittype;
		this.cartecreditnumero = cartecreditnumero;
		this.cartecreditdateexp = cartecreditdateexp;
		this.cartecreditcvv = cartecreditcvv;
	}

	public BigDecimal getIdutilisateur() {
		return this.idutilisateur;
	}

	public void setIdutilisateur(BigDecimal idutilisateur) {
		this.idutilisateur = idutilisateur;
	}

	public Forfait getForfait() {
		return this.forfait;
	}

	public void setForfait(Forfait forfait) {
		this.forfait = forfait;
	}

	public String getNomfamille() {
		return this.nomfamille;
	}

	public void setNomfamille(String nomfamille) {
		this.nomfamille = nomfamille;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getUtilisateurtype() {
		return this.utilisateurtype;
	}

	public void setUtilisateurtype(String utilisateurtype) {
		this.utilisateurtype = utilisateurtype;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getCourriel() {
		return this.courriel;
	}

	public void setCourriel(String courriel) {
		this.courriel = courriel;
	}

	public BigDecimal getNumerocivique() {
		return this.numerocivique;
	}

	public void setNumerocivique(BigDecimal numerocivique) {
		this.numerocivique = numerocivique;
	}

	public String getRue() {
		return this.rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCodepostal() {
		return this.codepostal;
	}

	public void setCodepostal(String codepostal) {
		this.codepostal = codepostal;
	}

	public Date getDatenaissance() {
		return this.datenaissance;
	}

	public void setDatenaissance(Date datenaissance) {
		this.datenaissance = datenaissance;
	}

	public String getIdentificateur() {
		return this.identificateur;
	}

	public void setIdentificateur(String identificateur) {
		this.identificateur = identificateur;
	}

	public String getMotdepasse() {
		return this.motdepasse;
	}

	public void setMotdepasse(String motdepasse) {
		this.motdepasse = motdepasse;
	}

	public String getCartecredittype() {
		return this.cartecredittype;
	}

	public void setCartecredittype(String cartecredittype) {
		this.cartecredittype = cartecredittype;
	}

	public Long getCartecreditnumero() {
		return this.cartecreditnumero;
	}

	public void setCartecreditnumero(Long cartecreditnumero) {
		this.cartecreditnumero = cartecreditnumero;
	}

	public Date getCartecreditdateexp() {
		return this.cartecreditdateexp;
	}

	public void setCartecreditdateexp(Date cartecreditdateexp) {
		this.cartecreditdateexp = cartecreditdateexp;
	}

	public Short getCartecreditcvv() {
		return this.cartecreditcvv;
	}

	public void setCartecreditcvv(Short cartecreditcvv) {
		this.cartecreditcvv = cartecreditcvv;
	}

}
